---
galaxy_info:
  author: Thomas Fauroux
  description: Configuration de base du système (hostname, timezone, packages essentiels)
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: EL
      versions: ["9"]
dependencies: []
