apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: layer-02-observability
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/thfx31/rncp_bloc05.git
    targetRevision: main
    path: kubernetes/02-observability
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
